#!/bin/sh

die () {
   echo "*** mkconfig: $*" 1>&2
   exit 1
}

[ -f makefile ] || die "can not find 'makefile'"

cat<<EOF
/**************************************************************/
/* Automatically generated by './mkconfig.sh'.  Do note edit! */
/**************************************************************/
EOF

echo "#define YALS_OS \"`uname -srmn`\""
echo "#define YALS_COMPILED \"`date`\""
echo "#define YALS_RELEASED \"Tue Apr 29 19:18:49 CEST 2014\""
echo "#define YALS_VERSION \"03l\""
echo "#define YALS_ID \"3742c36850f41a20c435f2eaf89205fd7e55fa03\""
